[package]
name = "pdf2docx"
version = "0.1.0"
edition = "2021"
default-run = "dump-pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.31.0"

[dev-dependencies]
hex = "0.4.3"

[features]
dump = []

[[bin]]
name = "dump-pdf"
required-features = ["dump"]
features = ["dump"]

