[package]
name = "pdf2docx"
version = "0.1.0"
edition = "2021"
default-run = "dump-pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.31.0"
hex = {version="0.4.3", optional=true}
clap = {version="4.3.0", optional=true, features=["derive"]}
anyhow = "1.0.71"
thiserror = "1.0.40"
educe = "0.4.22"
once_cell = "1.17.2"
strum = {version = "0.24.1", features=["derive"]}
memchr = "2.5.0"
itertools = "0.10.5"
flate2 = "1.0.26"
pdf = "0.8.1"
istring = "0.3.3"

[patch.crates-io]
lopdf = { git = "https://github.com/redforks/lopdf.git" }

[dev-dependencies]
test-case = "3.1.0"

[features]
dump = ["hex", "clap"]

[[bin]]
name = "dump-pdf"
required-features = ["dump"]

