[workspace]
members = ["nipdf", "nipdf-macro", "nipdf-dump", "nipdf-reader"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.insta]
opt-level = 3

[profile.release]
split-debuginfo = "unpacked"
lto = true
codegen-units=1

[profile.dev]
split-debuginfo = "unpacked"
