[workspace]
members = [
  "pdf2docx"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.insta]
opt-level = 3

[profile.release]
split-debuginfo = "unpacked"

[profile.dev]
split-debuginfo = "unpacked"
