[package]
name = "pdf2docx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = {version="0.4.3"}
thiserror = "1.0.40"
once_cell = "1.17.2"
itertools = "0.10.5"
nom = "7.1.3"
num = "0.4.0"
memchr = "2.5.0"

[dev-dependencies]
glob = "0.3.1"
insta = "1.29.0"
test-case = "3.1.0"

[profile.dev.package.insta]
opt-level = 3
