[package]
name = "pdf2docx"
version = "0.1.0"
edition = "2021"
default-run = "dump-pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.31.0"
hex = {version="0.4.3", optional=true}

[dev-dependencies]

[features]
dump = ["hex"]

[[bin]]
name = "dump-pdf"
required-features = ["dump"]
features = ["dump"]

