[package]
name = "pdf2docx"
version = "0.1.0"
edition = "2021"
default-run = "dump-pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = {version="0.4.3"}
clap = {version="4.3.0", optional=true, features=["derive"]}
anyhow = "1.0.71"
thiserror = "1.0.40"
educe = "0.4.22"
once_cell = "1.17.2"
strum = {version = "0.24.1", features=["derive"]}
itertools = "0.10.5"
pdf = "0.8.1"
istring = "0.3.3"
nom = "7.1.3"
num = "0.4.0"
memchr = "2.5.0"

[dev-dependencies]
glob = "0.3.1"
insta = "1.29.0"
test-case = "3.1.0"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[features]
dump = ["clap"]

[[bin]]
name = "dump-pdf"
required-features = ["dump"]

