use std::{collections::HashMap, convert::AsRef};

use bitflags::bitflags;
use log::debug;
use nipdf_macro::{pdf_object, TryFromIntObjectForBitflags, TryFromNameObject};

use crate::{
    file::Rectangle,
    graphics::{NameOrDictByRef, NameOrStream},
    object::{Object, ObjectValueError, Stream},
};

#[derive(Debug, Copy, Clone, PartialEq, Eq, TryFromNameObject)]
pub enum FontType {
    Type0,
    Type1,
    MMType1,
    Type3,
    TrueType,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, TryFromNameObject)]
pub enum CIDFontType {
    CIDFontType0,
    CIDFontType2,
}

#[pdf_object("Font")]
pub trait FontDictTrait {
    #[try_from]
    fn subtype(&self) -> FontType;

    #[self_as]
    fn type0(&self) -> Type0FontDict<'a, 'b>;

    #[self_as]
    fn type1(&self) -> Type1FontDict<'a, 'b>;

    #[self_as]
    fn truetype(&self) -> TrueTypeFontDict<'a, 'b>;
}

#[pdf_object(("Font", "Type0"))]
pub trait Type0FontDictTrait {
    #[typ("Name")]
    fn base_font(&self) -> &str;
    #[try_from]
    fn encoding(&self) -> NameOrStream<'a, 'b>;
    #[nested]
    fn descendant_fonts(&self) -> Vec<CIDFontDict<'a, 'b>>;
    fn to_unicode(&self) -> Option<&'b Stream<'a>>;
}

/// For standard 14 fonts, font_descriptor/first_char/last_char/widths may not exist.
/// they should all exist or not exist. See PDF32000_2008.pdf page 255
#[pdf_object(("Font", "Type1"))]
pub trait Type1FontDictTrait {
    #[typ("Name")]
    fn base_font(&self) -> &str;
    /// If font is the standard 14 fonts, it may not exist.
    fn first_char(&self) -> Option<u32>;
    /// if font is the standard 14 fonts, it may not exist.
    fn last_char(&self) -> Option<u32>;
    /// if font is the standard 14 fonts, it may not exist.
    fn widths(&self) -> Vec<u32>;
    /// if font is the standard 14 fonts, it may not exist.
    #[nested]
    fn font_descriptor(&self) -> Option<FontDescriptorDict<'a, 'b>>;
    #[try_from]
    fn encoding(&self) -> Option<NameOrDictByRef<'a, 'b>>;
    fn to_unicode(&self) -> Option<&'b Stream<'a>>;
}

impl<'a, 'b> Type1FontDict<'a, 'b> {
    fn resolve_name(&self) -> anyhow::Result<&str> {
        if let Some(desc) = self.font_descriptor()? {
            return Ok(desc.font_name()?);
        }

        self.base_font().map(|s| s.as_ref())
    }

    pub fn font_name(&self) -> anyhow::Result<&str> {
        let r = self.resolve_name()?;

        // if font is subset, the name will prefixed with a tag,
        // which is a string of 6 uppercase letters, followed by a plus sign (+).
        if r.len() > 7 && r.as_bytes()[6] == b'+' {
            Ok(&r[7..])
        } else {
            Ok(r)
        }
    }
}

#[pdf_object(("Font", "TrueType"))]
pub trait TrueTypeFontDictTrait {
    #[typ("Name")]
    fn base_font(&self) -> &str;
    fn first_char(&self) -> u32;
    fn last_char(&self) -> u32;
    fn widths(&self) -> Vec<u32>;
    #[nested]
    fn font_descriptor(&self) -> Option<FontDescriptorDict<'a, 'b>>;
    #[try_from]
    fn encoding(&self) -> Option<NameOrDictByRef<'a, 'b>>;
    fn to_unicode(&self) -> Option<&'b Stream<'a>>;
}

#[derive(Debug, PartialEq)]
pub enum CIDFontWidthGroup {
    NConsecutive((u32, Vec<u16>)),
    FirstLast { first: u32, last: u32, width: u16 },
}

#[derive(Debug, PartialEq)]
pub struct CIDFontWidths(Vec<CIDFontWidthGroup>);
impl CIDFontWidths {
    /// Return None if ch out of range
    pub(crate) fn char_width(&self, ch: u32) -> Option<u32> {
        for group in &self.0 {
            match group {
                CIDFontWidthGroup::NConsecutive((first, widths)) => {
                    if ch >= *first && ch < *first + widths.len() as u32 {
                        return Some(widths[(ch - first) as usize] as u32);
                    }
                }
                CIDFontWidthGroup::FirstLast { first, last, width } => {
                    if ch >= *first && ch <= *last {
                        return Some(*width as u32);
                    }
                }
            }
        }
        None
    }
}

impl<'a, 'b> TryFrom<&'b Object<'a>> for CIDFontWidths {
    type Error = ObjectValueError;

    fn try_from(obj: &'b Object<'a>) -> Result<Self, Self::Error> {
        let mut widths = Vec::new();
        let Object::Array(arr) = obj else {
            return Err(Self::Error::UnexpectedType);
        };

        let mut iter = arr.iter();
        while let Some(first) = iter.next() {
            let first = first.as_int()?;
            let second = iter.next().ok_or(Self::Error::UnexpectedType)?;
            match second {
                Object::Array(arr) => {
                    let mut width = Vec::with_capacity(arr.len());
                    for num in arr.iter() {
                        let num = num.as_int()? as u16;
                        width.push(num);
                    }
                    widths.push(CIDFontWidthGroup::NConsecutive((first as u32, width)));
                }
                Object::Integer(last) => {
                    let width = iter.next().ok_or(Self::Error::UnexpectedType)?;
                    widths.push(CIDFontWidthGroup::FirstLast {
                        first: first as u32,
                        last: *last as u32,
                        width: width.as_int()? as u16,
                    });
                }
                _ => return Err(Self::Error::UnexpectedType),
            }
        }
        Ok(CIDFontWidths(widths))
    }
}

#[pdf_object("Font")]
pub trait CIDFontDictTrait {
    #[try_from]
    fn subtype(&self) -> CIDFontType;
    #[typ("Name")]
    fn base_font(&self) -> &str;
    #[nested]
    fn font_descriptor(&self) -> Option<FontDescriptorDict<'a, 'b>>;
    #[default(1000u32)]
    fn dw(&self) -> u32;
    #[try_from]
    fn w(&self) -> CIDFontWidths;
    #[try_from]
    fn cid_to_gid_map(&self) -> Option<NameOrStream<'a, 'b>>;
}

#[pdf_object("FontDescriptor")]
pub trait FontDescriptorDictTrait {
    #[typ("Name")]
    fn font_name(&self) -> &'b str;

    fn font_family(&self) -> &str;

    #[typ("Name")]
    fn font_stretch(&self) -> Option<&str>;

    fn font_weight(&self) -> Option<u32>;

    #[try_from]
    fn flags(&self) -> FontDescriptorFlags;

    #[try_from]
    fn font_b_box(&self) -> Rectangle;

    fn italic_angle(&self) -> f32;

    fn ascent(&self) -> f32;

    fn descent(&self) -> f32;

    #[or_default]
    fn leading(&self) -> f32;

    fn cap_height(&self) -> Option<f32>;

    #[or_default]
    fn x_height(&self) -> f32;

    fn stem_v(&self) -> f32;

    #[or_default]
    fn stem_h(&self) -> f32;

    #[or_default]
    fn avg_width(&self) -> f32;

    #[or_default]
    fn max_width(&self) -> f32;

    #[or_default]
    fn missing_width(&self) -> u32;

    fn font_file(&self) -> Option<&'b Stream<'a>>;

    fn font_file2(&self) -> Option<&'b Stream<'a>>;

    fn font_file3(&self) -> Option<&'b Stream<'a>>;

    fn char_set(&self) -> Option<&str>;
}

bitflags! {
    #[derive(TryFromIntObjectForBitflags)]
    pub struct FontDescriptorFlags: u32 {
        const FIXED_PITCH = 1;
        const SERIF = 1 << 1;
        const SYMBOLIC = 1 << 2;
        const SCRIPT = 1 << 3;
        const NONSYMBOLIC = 1 << 5;
        const ITALIC = 1 << 6;
        const ALL_CAP = 1 << 16;
        const SMALL_CAP = 1 << 17;
        const FORCE_BOLD = 1 << 18;
    }
}

/// Map to pdf Encoding object Differences field. Override character code
/// to glyph names from BaseEncoding.
pub struct EncodingDifferences<'a>(HashMap<u8, &'a str>);

/// Parse Differences field in Encoding object, which is an array of
/// character code and one or several glyph names. First name is mapped
/// to character code, second name is mapped to character code + 1, and so on.
impl<'a, 'b> TryFrom<&'b Object<'a>> for EncodingDifferences<'b> {
    type Error = ObjectValueError;

    fn try_from(obj: &'b Object<'a>) -> Result<Self, Self::Error> {
        let mut map = HashMap::new();
        let Object::Array(arr) = obj else {
            return Err(Self::Error::UnexpectedType);
        };

        let mut iter = arr.iter();
        let Some(o) = iter.next() else {
            return Ok(EncodingDifferences(map));
        };

        let mut code = o.as_int()?;
        for o in iter {
            match o {
                Object::Name(name) => {
                    map.insert(code as u8, name.as_ref());
                    code += 1;
                }
                Object::Integer(num) => {
                    code = *num;
                }
                _ => return Err(Self::Error::UnexpectedType),
            };
        }
        Ok(EncodingDifferences(map))
    }
}

/// Encoding object for Non Type0 and Type3 fonts
#[pdf_object(Some("Encoding"))]
pub trait EncodingDictTrait {
    #[typ("Name")]
    fn base_encoding(&self) -> Option<&str>;

    #[try_from]
    fn differences(&self) -> Option<EncodingDifferences<'b>>;
}

/// Encoding for Type1
/// map char code (u8) to glyph name
#[derive(Debug)]
pub struct Encoding<'a>([Option<&'a str>; 256]);

impl<'a> Encoding<'a> {
    pub fn new(encodings: [Option<&'a str>; 256]) -> Self {
        Self(encodings)
    }

    pub fn decode(&self, ch: u8) -> Option<&'a str> {
        self.0[ch as usize]
    }

    pub fn apply_differences(&self, diff: &EncodingDifferences<'a>) -> Self {
        let mut new = self.0;
        for (ch, name) in diff.0.iter() {
            new[*ch as usize] = Some(*name);
        }
        Self(new)
    }
}

impl Encoding<'static> {
    pub fn predefined(name: &str) -> Option<Self> {
        match name {
            "MacRomanEncoding" => Some(Self::MAC_ROMAN),
            "MacExpertEncoding" => Some(Self::MAC_EXPORT),
            "WinAnsiEncoding" => Some(Self::WIN_ANSI),
            "StandardEncoding" => Some(Self::STANDARD),
            _ => None,
        }
    }

    pub const STANDARD: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclam"),
        Some("quotedbl"),
        Some("numbersign"),
        Some("dollar"),
        Some("percent"),
        Some("ampersand"),
        Some("quotesingle"),
        Some("parenleft"),
        Some("parenright"),
        Some("asterisk"),
        Some("plus"),
        Some("comma"),
        Some("hyphen"),
        Some("period"),
        Some("slash"),
        Some("zero"),
        Some("one"),
        Some("two"),
        Some("three"),
        Some("four"),
        Some("five"),
        Some("six"),
        Some("seven"),
        Some("eight"),
        Some("nine"),
        Some("colon"),
        Some("semicolon"),
        Some("less"),
        Some("equal"),
        Some("greater"),
        Some("question"),
        Some("at"),
        Some("A"),
        Some("B"),
        Some("C"),
        Some("D"),
        Some("E"),
        Some("F"),
        Some("G"),
        Some("H"),
        Some("I"),
        Some("J"),
        Some("K"),
        Some("L"),
        Some("M"),
        Some("N"),
        Some("O"),
        Some("P"),
        Some("Q"),
        Some("R"),
        Some("S"),
        Some("T"),
        Some("U"),
        Some("V"),
        Some("W"),
        Some("X"),
        Some("Y"),
        Some("Z"),
        Some("bracketleft"),
        Some("backslash"),
        Some("bracketright"),
        Some("asciicircum"),
        Some("underscore"),
        Some("grave"),
        Some("a"),
        Some("b"),
        Some("c"),
        Some("d"),
        Some("e"),
        Some("f"),
        Some("g"),
        Some("h"),
        Some("i"),
        Some("j"),
        Some("k"),
        Some("l"),
        Some("m"),
        Some("n"),
        Some("o"),
        Some("p"),
        Some("q"),
        Some("r"),
        Some("s"),
        Some("t"),
        Some("u"),
        Some("v"),
        Some("w"),
        Some("x"),
        Some("y"),
        Some("z"),
        Some("braceleft"),
        Some("bar"),
        Some("braceright"),
        Some("asciitilde"),
        Some("bullet"),
        Some("Euro"),
        Some("bullet"),
        Some("quotesinglbase"),
        Some("florin"),
        Some("quotedblbase"),
        Some("ellipsis"),
        Some("dagger"),
        Some("daggerdbl"),
        Some("circumflex"),
        Some("perthousand"),
        Some("Scaron"),
        Some("guilsinglleft"),
        Some("OE"),
        Some("bullet"),
        Some("Zcaron"),
        Some("bullet"),
        Some("bullet"),
        Some("quoteleft"),
        Some("quoteright"),
        Some("quotedblleft"),
        Some("quotedblright"),
        Some("bullet"),
        Some("endash"),
        Some("emdash"),
        Some("tilde"),
        Some("trademark"),
        Some("scaron"),
        Some("guilsinglright"),
        Some("oe"),
        Some("bullet"),
        Some("zcaron"),
        Some("Ydieresis"),
        Some("space"),
        Some("exclamdown"),
        Some("cent"),
        Some("sterling"),
        Some("currency"),
        Some("yen"),
        Some("brokenbar"),
        Some("section"),
        Some("dieresis"),
        Some("copyright"),
        Some("ordfeminine"),
        Some("guillemotleft"),
        Some("logicalnot"),
        Some("hyphen"),
        Some("registered"),
        Some("macron"),
        Some("degree"),
        Some("plusminus"),
        Some("twosuperior"),
        Some("threesuperior"),
        Some("acute"),
        Some("mu"),
        Some("paragraph"),
        Some("periodcentered"),
        Some("cedilla"),
        Some("onesuperior"),
        Some("ordmasculine"),
        Some("guillemotright"),
        Some("onequarter"),
        Some("onehalf"),
        Some("threequarters"),
        Some("questiondown"),
        Some("Agrave"),
        Some("Aacute"),
        Some("Acircumflex"),
        Some("Atilde"),
        Some("Adieresis"),
        Some("Aring"),
        Some("AE"),
        Some("Ccedilla"),
        Some("Egrave"),
        Some("Eacute"),
        Some("Ecircumflex"),
        Some("Edieresis"),
        Some("Igrave"),
        Some("Iacute"),
        Some("Icircumflex"),
        Some("Idieresis"),
        Some("Eth"),
        Some("Ntilde"),
        Some("Ograve"),
        Some("Oacute"),
        Some("Ocircumflex"),
        Some("Otilde"),
        Some("Odieresis"),
        Some("multiply"),
        Some("Oslash"),
        Some("Ugrave"),
        Some("Uacute"),
        Some("Ucircumflex"),
        Some("Udieresis"),
        Some("Yacute"),
        Some("Thorn"),
        Some("germandbls"),
        Some("agrave"),
        Some("aacute"),
        Some("acircumflex"),
        Some("atilde"),
        Some("adieresis"),
        Some("aring"),
        Some("ae"),
        Some("ccedilla"),
        Some("egrave"),
        Some("eacute"),
        Some("ecircumflex"),
        Some("edieresis"),
        Some("igrave"),
        Some("iacute"),
        Some("icircumflex"),
        Some("idieresis"),
        Some("eth"),
        Some("ntilde"),
        Some("ograve"),
        Some("oacute"),
        Some("ocircumflex"),
        Some("otilde"),
        Some("odieresis"),
        Some("divide"),
        Some("oslash"),
        Some("ugrave"),
        Some("uacute"),
        Some("ucircumflex"),
        Some("udieresis"),
        Some("yacute"),
        Some("thorn"),
        Some("ydieresis"),
    ]);

    pub const MAC_ROMAN: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclam"),
        Some("quotedbl"),
        Some("numbersign"),
        Some("dollar"),
        Some("percent"),
        Some("ampersand"),
        Some("quotesingle"),
        Some("parenleft"),
        Some("parenright"),
        Some("asterisk"),
        Some("plus"),
        Some("comma"),
        Some("hyphen"),
        Some("period"),
        Some("slash"),
        Some("zero"),
        Some("one"),
        Some("two"),
        Some("three"),
        Some("four"),
        Some("five"),
        Some("six"),
        Some("seven"),
        Some("eight"),
        Some("nine"),
        Some("colon"),
        Some("semicolon"),
        Some("less"),
        Some("equal"),
        Some("greater"),
        Some("question"),
        Some("at"),
        Some("A"),
        Some("B"),
        Some("C"),
        Some("D"),
        Some("E"),
        Some("F"),
        Some("G"),
        Some("H"),
        Some("I"),
        Some("J"),
        Some("K"),
        Some("L"),
        Some("M"),
        Some("N"),
        Some("O"),
        Some("P"),
        Some("Q"),
        Some("R"),
        Some("S"),
        Some("T"),
        Some("U"),
        Some("V"),
        Some("W"),
        Some("X"),
        Some("Y"),
        Some("Z"),
        Some("bracketleft"),
        Some("backslash"),
        Some("bracketright"),
        Some("asciicircum"),
        Some("underscore"),
        Some("grave"),
        Some("a"),
        Some("b"),
        Some("c"),
        Some("d"),
        Some("e"),
        Some("f"),
        Some("g"),
        Some("h"),
        Some("i"),
        Some("j"),
        Some("k"),
        Some("l"),
        Some("m"),
        Some("n"),
        Some("o"),
        Some("p"),
        Some("q"),
        Some("r"),
        Some("s"),
        Some("t"),
        Some("u"),
        Some("v"),
        Some("w"),
        Some("x"),
        Some("y"),
        Some("z"),
        Some("braceleft"),
        Some("bar"),
        Some("braceright"),
        Some("asciitilde"),
        None,
        Some("Adieresis"),
        Some("Aring"),
        Some("Ccedilla"),
        Some("Eacute"),
        Some("Ntilde"),
        Some("Odieresis"),
        Some("Udieresis"),
        Some("aacute"),
        Some("agrave"),
        Some("acircumflex"),
        Some("adieresis"),
        Some("atilde"),
        Some("aring"),
        Some("ccedilla"),
        Some("eacute"),
        Some("egrave"),
        Some("ecircumflex"),
        Some("edieresis"),
        Some("iacute"),
        Some("igrave"),
        Some("icircumflex"),
        Some("idieresis"),
        Some("ntilde"),
        Some("oacute"),
        Some("ograve"),
        Some("ocircumflex"),
        Some("odieresis"),
        Some("otilde"),
        Some("uacute"),
        Some("ugrave"),
        Some("ucircumflex"),
        Some("udieresis"),
        Some("dagger"),
        Some("degree"),
        Some("cent"),
        Some("sterling"),
        Some("section"),
        Some("bullet"),
        Some("paragraph"),
        Some("germandbls"),
        Some("registered"),
        Some("copyright"),
        Some("trademark"),
        Some("acute"),
        Some("dieresis"),
        Some("notequal"),
        Some("AE"),
        Some("Oslash"),
        Some("infinity"),
        Some("plusminus"),
        Some("lessequal"),
        Some("greaterequal"),
        Some("yen"),
        Some("mu"),
        Some("partialdiff"),
        Some("summation"),
        Some("product"),
        Some("pi"),
        Some("integral"),
        Some("ordfeminine"),
        Some("ordmasculine"),
        Some("Omega"),
        Some("ae"),
        Some("oslash"),
        Some("questiondown"),
        Some("exclamdown"),
        Some("logicalnot"),
        Some("radical"),
        Some("florin"),
        Some("approxequal"),
        Some("Delta"),
        Some("guillemotleft"),
        Some("guillemotright"),
        Some("ellipsis"),
        Some("space"),
        Some("Agrave"),
        Some("Atilde"),
        Some("Otilde"),
        Some("OE"),
        Some("oe"),
        Some("endash"),
        Some("emdash"),
        Some("quotedblleft"),
        Some("quotedblright"),
        Some("quoteleft"),
        Some("quoteright"),
        Some("divide"),
        Some("lozenge"),
        Some("ydieresis"),
        Some("Ydieresis"),
        Some("fraction"),
        Some("currency"),
        Some("guilsinglleft"),
        Some("guilsinglright"),
        Some("fi"),
        Some("fl"),
        Some("daggerdbl"),
        Some("periodcentered"),
        Some("quotesinglbase"),
        Some("quotedblbase"),
        Some("perthousand"),
        Some("Acircumflex"),
        Some("Ecircumflex"),
        Some("Aacute"),
        Some("Edieresis"),
        Some("Egrave"),
        Some("Iacute"),
        Some("Icircumflex"),
        Some("Idieresis"),
        Some("Igrave"),
        Some("Oacute"),
        Some("Ocircumflex"),
        Some("apple"),
        Some("Ograve"),
        Some("Uacute"),
        Some("Ucircumflex"),
        Some("Ugrave"),
        Some("dotlessi"),
        Some("circumflex"),
        Some("tilde"),
        Some("macron"),
        Some("breve"),
        Some("dotaccent"),
        Some("ring"),
        Some("cedilla"),
        Some("hungarumlaut"),
        Some("ogonek"),
        Some("caron"),
    ]);

    pub const MAC_EXPORT: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclamsmall"),
        Some("Hungarumlautsmall"),
        Some("centoldstyle"),
        Some("dollaroldstyle"),
        Some("dollarsuperior"),
        Some("ampersandsmall"),
        Some("Acutesmall"),
        Some("parenleftsuperior"),
        Some("parenrightsuperior"),
        Some("twodotenleader"),
        Some("onedotenleader"),
        Some("comma"),
        Some("hyphen"),
        Some("period"),
        Some("fraction"),
        Some("zerooldstyle"),
        Some("oneoldstyle"),
        Some("twooldstyle"),
        Some("threeoldstyle"),
        Some("fouroldstyle"),
        Some("fiveoldstyle"),
        Some("sixoldstyle"),
        Some("sevenoldstyle"),
        Some("eightoldstyle"),
        Some("nineoldstyle"),
        Some("colon"),
        Some("semicolon"),
        None,
        Some("threequartersemdash"),
        None,
        Some("questionsmall"),
        None,
        None,
        None,
        None,
        Some("Ethsmall"),
        None,
        None,
        Some("onequarter"),
        Some("onehalf"),
        Some("threequarters"),
        Some("oneeighth"),
        Some("threeeighths"),
        Some("fiveeighths"),
        Some("seveneighths"),
        Some("onethird"),
        Some("twothirds"),
        None,
        None,
        None,
        None,
        None,
        None,
        Some("ff"),
        Some("fi"),
        Some("fl"),
        Some("ffi"),
        Some("ffl"),
        Some("parenleftinferior"),
        None,
        Some("parenrightinferior"),
        Some("Circumflexsmall"),
        Some("hypheninferior"),
        Some("Gravesmall"),
        Some("Asmall"),
        Some("Bsmall"),
        Some("Csmall"),
        Some("Dsmall"),
        Some("Esmall"),
        Some("Fsmall"),
        Some("Gsmall"),
        Some("Hsmall"),
        Some("Ismall"),
        Some("Jsmall"),
        Some("Ksmall"),
        Some("Lsmall"),
        Some("Msmall"),
        Some("Nsmall"),
        Some("Osmall"),
        Some("Psmall"),
        Some("Qsmall"),
        Some("Rsmall"),
        Some("Ssmall"),
        Some("Tsmall"),
        Some("Usmall"),
        Some("Vsmall"),
        Some("Wsmall"),
        Some("Xsmall"),
        Some("Ysmall"),
        Some("Zsmall"),
        Some("colonmonetary"),
        Some("onefitted"),
        Some("rupiah"),
        Some("Tildesmall"),
        None,
        None,
        Some("asuperior"),
        Some("centsuperior"),
        None,
        None,
        None,
        None,
        Some("Aacutesmall"),
        Some("Agravesmall"),
        Some("Acircumflexsmall"),
        Some("Adieresissmall"),
        Some("Atildesmall"),
        Some("Aringsmall"),
        Some("Ccedillasmall"),
        Some("Eacutesmall"),
        Some("Egravesmall"),
        Some("Ecircumflexsmall"),
        Some("Edieresissmall"),
        Some("Iacutesmall"),
        Some("Igravesmall"),
        Some("Icircumflexsmall"),
        Some("Idieresissmall"),
        Some("Ntildesmall"),
        Some("Oacutesmall"),
        Some("Ogravesmall"),
        Some("Ocircumflexsmall"),
        Some("Odieresissmall"),
        Some("Otildesmall"),
        Some("Uacutesmall"),
        Some("Ugravesmall"),
        Some("Ucircumflexsmall"),
        Some("Udieresissmall"),
        None,
        Some("eightsuperior"),
        Some("fourinferior"),
        Some("threeinferior"),
        Some("sixinferior"),
        Some("eightinferior"),
        Some("seveninferior"),
        Some("Scaronsmall"),
        None,
        Some("centinferior"),
        Some("twoinferior"),
        None,
        Some("Dieresissmall"),
        None,
        Some("Caronsmall"),
        Some("osuperior"),
        Some("fiveinferior"),
        None,
        Some("commainferior"),
        Some("periodinferior"),
        Some("Yacutesmall"),
        None,
        Some("dollarinferior"),
        None,
        None,
        Some("Thornsmall"),
        None,
        Some("nineinferior"),
        Some("zeroinferior"),
        Some("Zcaronsmall"),
        Some("AEsmall"),
        Some("Oslashsmall"),
        Some("questiondownsmall"),
        Some("oneinferior"),
        Some("Lslashsmall"),
        None,
        None,
        None,
        None,
        None,
        None,
        Some("Cedillasmall"),
        None,
        None,
        None,
        None,
        None,
        Some("OEsmall"),
        Some("figuredash"),
        Some("hyphensuperior"),
        None,
        None,
        None,
        None,
        Some("exclamdownsmall"),
        None,
        Some("Ydieresissmall"),
        None,
        Some("onesuperior"),
        Some("twosuperior"),
        Some("threesuperior"),
        Some("foursuperior"),
        Some("fivesuperior"),
        Some("sixsuperior"),
        Some("sevensuperior"),
        Some("ninesuperior"),
        Some("zerosuperior"),
        None,
        Some("esuperior"),
        Some("rsuperior"),
        Some("tsuperior"),
        None,
        None,
        Some("isuperior"),
        Some("ssuperior"),
        Some("dsuperior"),
        None,
        None,
        None,
        None,
        None,
        Some("lsuperior"),
        Some("Ogoneksmall"),
        Some("Brevesmall"),
        Some("Macronsmall"),
        Some("bsuperior"),
        Some("nsuperior"),
        Some("msuperior"),
        Some("commasuperior"),
        Some("periodsuperior"),
        Some("Dotaccentsmall"),
        Some("Ringsmall"),
        None,
        None,
        None,
        None,
    ]);

    pub const WIN_ANSI: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclam"),
        Some("quotedbl"),
        Some("numbersign"),
        Some("dollar"),
        Some("percent"),
        Some("ampersand"),
        Some("quotesingle"),
        Some("parenleft"),
        Some("parenright"),
        Some("asterisk"),
        Some("plus"),
        Some("comma"),
        Some("hyphen"),
        Some("period"),
        Some("slash"),
        Some("zero"),
        Some("one"),
        Some("two"),
        Some("three"),
        Some("four"),
        Some("five"),
        Some("six"),
        Some("seven"),
        Some("eight"),
        Some("nine"),
        Some("colon"),
        Some("semicolon"),
        Some("less"),
        Some("equal"),
        Some("greater"),
        Some("question"),
        Some("at"),
        Some("A"),
        Some("B"),
        Some("C"),
        Some("D"),
        Some("E"),
        Some("F"),
        Some("G"),
        Some("H"),
        Some("I"),
        Some("J"),
        Some("K"),
        Some("L"),
        Some("M"),
        Some("N"),
        Some("O"),
        Some("P"),
        Some("Q"),
        Some("R"),
        Some("S"),
        Some("T"),
        Some("U"),
        Some("V"),
        Some("W"),
        Some("X"),
        Some("Y"),
        Some("Z"),
        Some("bracketleft"),
        Some("backslash"),
        Some("bracketright"),
        Some("asciicircum"),
        Some("underscore"),
        Some("grave"),
        Some("a"),
        Some("b"),
        Some("c"),
        Some("d"),
        Some("e"),
        Some("f"),
        Some("g"),
        Some("h"),
        Some("i"),
        Some("j"),
        Some("k"),
        Some("l"),
        Some("m"),
        Some("n"),
        Some("o"),
        Some("p"),
        Some("q"),
        Some("r"),
        Some("s"),
        Some("t"),
        Some("u"),
        Some("v"),
        Some("w"),
        Some("x"),
        Some("y"),
        Some("z"),
        Some("braceleft"),
        Some("bar"),
        Some("braceright"),
        Some("asciitilde"),
        Some("bullet"),
        Some("Euro"),
        Some("bullet"),
        Some("quotesinglbase"),
        Some("florin"),
        Some("quotedblbase"),
        Some("ellipsis"),
        Some("dagger"),
        Some("daggerdbl"),
        Some("circumflex"),
        Some("perthousand"),
        Some("Scaron"),
        Some("guilsinglleft"),
        Some("OE"),
        Some("bullet"),
        Some("Zcaron"),
        Some("bullet"),
        Some("bullet"),
        Some("quoteleft"),
        Some("quoteright"),
        Some("quotedblleft"),
        Some("quotedblright"),
        Some("bullet"),
        Some("endash"),
        Some("emdash"),
        Some("tilde"),
        Some("trademark"),
        Some("scaron"),
        Some("guilsinglright"),
        Some("oe"),
        Some("bullet"),
        Some("zcaron"),
        Some("Ydieresis"),
        Some("space"),
        Some("exclamdown"),
        Some("cent"),
        Some("sterling"),
        Some("currency"),
        Some("yen"),
        Some("brokenbar"),
        Some("section"),
        Some("dieresis"),
        Some("copyright"),
        Some("ordfeminine"),
        Some("guillemotleft"),
        Some("logicalnot"),
        Some("hyphen"),
        Some("registered"),
        Some("macron"),
        Some("degree"),
        Some("plusminus"),
        Some("twosuperior"),
        Some("threesuperior"),
        Some("acute"),
        Some("mu"),
        Some("paragraph"),
        Some("periodcentered"),
        Some("cedilla"),
        Some("onesuperior"),
        Some("ordmasculine"),
        Some("guillemotright"),
        Some("onequarter"),
        Some("onehalf"),
        Some("threequarters"),
        Some("questiondown"),
        Some("Agrave"),
        Some("Aacute"),
        Some("Acircumflex"),
        Some("Atilde"),
        Some("Adieresis"),
        Some("Aring"),
        Some("AE"),
        Some("Ccedilla"),
        Some("Egrave"),
        Some("Eacute"),
        Some("Ecircumflex"),
        Some("Edieresis"),
        Some("Igrave"),
        Some("Iacute"),
        Some("Icircumflex"),
        Some("Idieresis"),
        Some("Eth"),
        Some("Ntilde"),
        Some("Ograve"),
        Some("Oacute"),
        Some("Ocircumflex"),
        Some("Otilde"),
        Some("Odieresis"),
        Some("multiply"),
        Some("Oslash"),
        Some("Ugrave"),
        Some("Uacute"),
        Some("Ucircumflex"),
        Some("Udieresis"),
        Some("Yacute"),
        Some("Thorn"),
        Some("germandbls"),
        Some("agrave"),
        Some("aacute"),
        Some("acircumflex"),
        Some("atilde"),
        Some("adieresis"),
        Some("aring"),
        Some("ae"),
        Some("ccedilla"),
        Some("egrave"),
        Some("eacute"),
        Some("ecircumflex"),
        Some("edieresis"),
        Some("igrave"),
        Some("iacute"),
        Some("icircumflex"),
        Some("idieresis"),
        Some("eth"),
        Some("ntilde"),
        Some("ograve"),
        Some("oacute"),
        Some("ocircumflex"),
        Some("otilde"),
        Some("odieresis"),
        Some("divide"),
        Some("oslash"),
        Some("ugrave"),
        Some("uacute"),
        Some("ucircumflex"),
        Some("udieresis"),
        Some("yacute"),
        Some("thorn"),
        Some("ydieresis"),
    ]);

    pub const SYMBOL: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclam"),
        Some("universal"),
        Some("numbersign"),
        Some("existential"),
        Some("percent"),
        Some("ampersand"),
        Some("suchthat"),
        Some("parenleft"),
        Some("parenright"),
        Some("asteriskmath"),
        Some("plus"),
        Some("comma"),
        Some("minus"),
        Some("period"),
        Some("slash"),
        Some("zero"),
        Some("one"),
        Some("two"),
        Some("three"),
        Some("four"),
        Some("five"),
        Some("six"),
        Some("seven"),
        Some("eight"),
        Some("nine"),
        Some("colon"),
        Some("semicolon"),
        Some("less"),
        Some("equal"),
        Some("greater"),
        Some("question"),
        Some("congruent"),
        Some("Alpha"),
        Some("Beta"),
        Some("Chi"),
        Some("Delta"),
        Some("Epsilon"),
        Some("Phi"),
        Some("Gamma"),
        Some("Eta"),
        Some("Iota"),
        Some("theta1"),
        Some("Kappa"),
        Some("Lambda"),
        Some("Mu"),
        Some("Nu"),
        Some("Omicron"),
        Some("Pi"),
        Some("Theta"),
        Some("Rho"),
        Some("Sigma"),
        Some("Tau"),
        Some("Upsilon"),
        Some("sigma1"),
        Some("Omega"),
        Some("Xi"),
        Some("Psi"),
        Some("Zeta"),
        Some("bracketleft"),
        Some("therefore"),
        Some("bracketright"),
        Some("perpendicular"),
        Some("underscore"),
        Some("radicalex"),
        Some("alpha"),
        Some("beta"),
        Some("chi"),
        Some("delta"),
        Some("epsilon"),
        Some("phi"),
        Some("gamma"),
        Some("eta"),
        Some("iota"),
        Some("phi1"),
        Some("kappa"),
        Some("lambda"),
        Some("mu"),
        Some("nu"),
        Some("omicron"),
        Some("pi"),
        Some("theta"),
        Some("rho"),
        Some("sigma"),
        Some("tau"),
        Some("upsilon"),
        Some("omega1"),
        Some("omega"),
        Some("xi"),
        Some("psi"),
        Some("zeta"),
        Some("braceleft"),
        Some("bar"),
        Some("braceright"),
        Some("similar"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("Upsilon1"),
        Some("minute"),
        Some("lessequal"),
        Some("fraction"),
        Some("infinity"),
        Some("florin"),
        Some("club"),
        Some("diamond"),
        Some("heart"),
        Some("spade"),
        Some("arrowboth"),
        Some("arrowleft"),
        Some("arrowup"),
        Some("arrowright"),
        Some("arrowdown"),
        Some("degree"),
        Some("plusminus"),
        Some("second"),
        Some("greaterequal"),
        Some("multiply"),
        Some("proportional"),
        Some("partialdiff"),
        Some("bullet"),
        Some("divide"),
        Some("notequal"),
        Some("equivalence"),
        Some("approxequal"),
        Some("ellipsis"),
        Some("arrowvertex"),
        Some("arrowhorizex"),
        Some("carriagereturn"),
        Some("aleph"),
        Some("Ifraktur"),
        Some("Rfraktur"),
        Some("weierstrass"),
        Some("circlemultiply"),
        Some("circleplus"),
        Some("emptyset"),
        Some("intersection"),
        Some("union"),
        Some("propersuperset"),
        Some("reflexsuperset"),
        Some("notsubset"),
        Some("propersubset"),
        Some("reflexsubset"),
        Some("element"),
        Some("notelement"),
        Some("angle"),
        Some("gradient"),
        Some("registerserif"),
        Some("copyrightserif"),
        Some("trademarkserif"),
        Some("product"),
        Some("radical"),
        Some("dotmath"),
        Some("logicalnot"),
        Some("logicaland"),
        Some("logicalor"),
        Some("arrowdblboth"),
        Some("arrowdblleft"),
        Some("arrowdblup"),
        Some("arrowdblright"),
        Some("arrowdbldown"),
        Some("lozenge"),
        Some("angleleft"),
        Some("registersans"),
        Some("copyrightsans"),
        Some("trademarksans"),
        Some("summation"),
        Some("parenlefttp"),
        Some("parenleftex"),
        Some("parenleftbt"),
        Some("bracketlefttp"),
        Some("bracketleftex"),
        Some("bracketleftbt"),
        Some("bracelefttp"),
        Some("braceleftmid"),
        Some("braceleftbt"),
        Some("braceex"),
        None,
        Some("angleright"),
        Some("integral"),
        Some("integraltp"),
        Some("integralex"),
        Some("integralbt"),
        Some("parenrighttp"),
        Some("parenrightex"),
        Some("parenrightbt"),
        Some("bracketrighttp"),
        Some("bracketrightex"),
        Some("bracketrightbt"),
        Some("bracerighttp"),
        Some("bracerightmid"),
        Some("bracerightbt"),
        None,
    ]);

    pub const ZAPFDINGBATS: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("a1"),
        Some("a2"),
        Some("a202"),
        Some("a3"),
        Some("a4"),
        Some("a5"),
        Some("a119"),
        Some("a118"),
        Some("a117"),
        Some("a11"),
        Some("a12"),
        Some("a13"),
        Some("a14"),
        Some("a15"),
        Some("a16"),
        Some("a105"),
        Some("a17"),
        Some("a18"),
        Some("a19"),
        Some("a20"),
        Some("a21"),
        Some("a22"),
        Some("a23"),
        Some("a24"),
        Some("a25"),
        Some("a26"),
        Some("a27"),
        Some("a28"),
        Some("a6"),
        Some("a7"),
        Some("a8"),
        Some("a9"),
        Some("a10"),
        Some("a29"),
        Some("a30"),
        Some("a31"),
        Some("a32"),
        Some("a33"),
        Some("a34"),
        Some("a35"),
        Some("a36"),
        Some("a37"),
        Some("a38"),
        Some("a39"),
        Some("a40"),
        Some("a41"),
        Some("a42"),
        Some("a43"),
        Some("a44"),
        Some("a45"),
        Some("a46"),
        Some("a47"),
        Some("a48"),
        Some("a49"),
        Some("a50"),
        Some("a51"),
        Some("a52"),
        Some("a53"),
        Some("a54"),
        Some("a55"),
        Some("a56"),
        Some("a57"),
        Some("a58"),
        Some("a59"),
        Some("a60"),
        Some("a61"),
        Some("a62"),
        Some("a63"),
        Some("a64"),
        Some("a65"),
        Some("a66"),
        Some("a67"),
        Some("a68"),
        Some("a69"),
        Some("a70"),
        Some("a71"),
        Some("a72"),
        Some("a73"),
        Some("a74"),
        Some("a203"),
        Some("a75"),
        Some("a204"),
        Some("a76"),
        Some("a77"),
        Some("a78"),
        Some("a79"),
        Some("a81"),
        Some("a82"),
        Some("a83"),
        Some("a84"),
        Some("a97"),
        Some("a98"),
        Some("a99"),
        Some("a100"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("a101"),
        Some("a102"),
        Some("a103"),
        Some("a104"),
        Some("a106"),
        Some("a107"),
        Some("a108"),
        Some("a112"),
        Some("a111"),
        Some("a110"),
        Some("a109"),
        Some("a120"),
        Some("a121"),
        Some("a122"),
        Some("a123"),
        Some("a124"),
        Some("a125"),
        Some("a126"),
        Some("a127"),
        Some("a128"),
        Some("a129"),
        Some("a130"),
        Some("a131"),
        Some("a132"),
        Some("a133"),
        Some("a134"),
        Some("a135"),
        Some("a136"),
        Some("a137"),
        Some("a138"),
        Some("a139"),
        Some("a140"),
        Some("a141"),
        Some("a142"),
        Some("a143"),
        Some("a144"),
        Some("a145"),
        Some("a146"),
        Some("a147"),
        Some("a148"),
        Some("a149"),
        Some("a150"),
        Some("a151"),
        Some("a152"),
        Some("a153"),
        Some("a154"),
        Some("a155"),
        Some("a156"),
        Some("a157"),
        Some("a158"),
        Some("a159"),
        Some("a160"),
        Some("a161"),
        Some("a163"),
        Some("a164"),
        Some("a196"),
        Some("a165"),
        Some("a192"),
        Some("a166"),
        Some("a167"),
        Some("a168"),
        Some("a169"),
        Some("a170"),
        Some("a171"),
        Some("a172"),
        Some("a173"),
        Some("a162"),
        Some("a174"),
        Some("a175"),
        Some("a176"),
        Some("a177"),
        Some("a178"),
        Some("a179"),
        Some("a193"),
        Some("a180"),
        Some("a199"),
        Some("a181"),
        Some("a200"),
        Some("a182"),
        None,
        Some("a201"),
        Some("a183"),
        Some("a184"),
        Some("a197"),
        Some("a185"),
        Some("a194"),
        Some("a198"),
        Some("a186"),
        Some("a195"),
        Some("a187"),
        Some("a188"),
        Some("a189"),
        Some("a190"),
        Some("a191"),
        None,
    ]);

    pub const EXPERT: Self = Self([
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("space"),
        Some("exclamsmall"),
        Some("Hungarumlautsmall"),
        None,
        Some("dollaroldstyle"),
        Some("dollarsuperior"),
        Some("ampersandsmall"),
        Some("Acutesmall"),
        Some("parenleftsuperior"),
        Some("parenrightsuperior"),
        Some("twodotenleader"),
        Some("onedotenleader"),
        Some("comma"),
        Some("hyphen"),
        Some("period"),
        Some("fraction"),
        Some("zerooldstyle"),
        Some("oneoldstyle"),
        Some("twooldstyle"),
        Some("threeoldstyle"),
        Some("fouroldstyle"),
        Some("fiveoldstyle"),
        Some("sixoldstyle"),
        Some("sevenoldstyle"),
        Some("eightoldstyle"),
        Some("nineoldstyle"),
        Some("colon"),
        Some("semicolon"),
        Some("commasuperior"),
        Some("threequartersemdash"),
        Some("periodsuperior"),
        Some("questionsmall"),
        None,
        Some("asuperior"),
        Some("bsuperior"),
        Some("centsuperior"),
        Some("dsuperior"),
        Some("esuperior"),
        None,
        None,
        None,
        Some("isuperior"),
        None,
        None,
        Some("lsuperior"),
        Some("msuperior"),
        Some("nsuperior"),
        Some("osuperior"),
        None,
        None,
        Some("rsuperior"),
        Some("ssuperior"),
        Some("tsuperior"),
        None,
        Some("ff"),
        Some("fi"),
        Some("fl"),
        Some("ffi"),
        Some("ffl"),
        Some("parenleftinferior"),
        None,
        Some("parenrightinferior"),
        Some("Circumflexsmall"),
        Some("hyphensuperior"),
        Some("Gravesmall"),
        Some("Asmall"),
        Some("Bsmall"),
        Some("Csmall"),
        Some("Dsmall"),
        Some("Esmall"),
        Some("Fsmall"),
        Some("Gsmall"),
        Some("Hsmall"),
        Some("Ismall"),
        Some("Jsmall"),
        Some("Ksmall"),
        Some("Lsmall"),
        Some("Msmall"),
        Some("Nsmall"),
        Some("Osmall"),
        Some("Psmall"),
        Some("Qsmall"),
        Some("Rsmall"),
        Some("Ssmall"),
        Some("Tsmall"),
        Some("Usmall"),
        Some("Vsmall"),
        Some("Wsmall"),
        Some("Xsmall"),
        Some("Ysmall"),
        Some("Zsmall"),
        Some("colonmonetary"),
        Some("onefitted"),
        Some("rupiah"),
        Some("Tildesmall"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some("exclamdownsmall"),
        Some("centoldstyle"),
        Some("Lslashsmall"),
        None,
        None,
        Some("Scaronsmall"),
        Some("Zcaronsmall"),
        Some("Dieresissmall"),
        Some("Brevesmall"),
        Some("Caronsmall"),
        None,
        Some("Dotaccentsmall"),
        None,
        None,
        Some("Macronsmall"),
        None,
        None,
        Some("figuredash"),
        Some("hypheninferior"),
        None,
        None,
        Some("Ogoneksmall"),
        Some("Ringsmall"),
        Some("Cedillasmall"),
        None,
        None,
        None,
        Some("onequarter"),
        Some("onehalf"),
        Some("threequarters"),
        Some("questiondownsmall"),
        Some("oneeighth"),
        Some("threeeighths"),
        Some("fiveeighths"),
        Some("seveneighths"),
        Some("onethird"),
        Some("twothirds"),
        None,
        None,
        Some("zerosuperior"),
        Some("onesuperior"),
        Some("twosuperior"),
        Some("threesuperior"),
        Some("foursuperior"),
        Some("fivesuperior"),
        Some("sixsuperior"),
        Some("sevensuperior"),
        Some("eightsuperior"),
        Some("ninesuperior"),
        Some("zeroinferior"),
        Some("oneinferior"),
        Some("twoinferior"),
        Some("threeinferior"),
        Some("fourinferior"),
        Some("fiveinferior"),
        Some("sixinferior"),
        Some("seveninferior"),
        Some("eightinferior"),
        Some("nineinferior"),
        Some("centinferior"),
        Some("dollarinferior"),
        Some("periodinferior"),
        Some("commainferior"),
        Some("Agravesmall"),
        Some("Aacutesmall"),
        Some("Acircumflexsmall"),
        Some("Atildesmall"),
        Some("Adieresissmall"),
        Some("Aringsmall"),
        Some("AEsmall"),
        Some("Ccedillasmall"),
        Some("Egravesmall"),
        Some("Eacutesmall"),
        Some("Ecircumflexsmall"),
        Some("Edieresissmall"),
        Some("Igravesmall"),
        Some("Iacutesmall"),
        Some("Icircumflexsmall"),
        Some("Idieresissmall"),
        Some("Ethsmall"),
        Some("Ntildesmall"),
        Some("Ogravesmall"),
        Some("Oacutesmall"),
        Some("Ocircumflexsmall"),
        Some("Otildesmall"),
        Some("Odieresissmall"),
        Some("OEsmall"),
        Some("Oslashsmall"),
        Some("Ugravesmall"),
        Some("Uacutesmall"),
        Some("Ucircumflexsmall"),
        Some("Udieresissmall"),
        Some("Yacutesmall"),
        Some("Thornsmall"),
        Some("Ydieresissmall"),
    ]);
}

#[cfg(test)]
mod tests;
