[package]
name = "nipdf-dump"
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nipdf = { path = "../nipdf" }
nipdf-render = { path = "../render" }
env_logger.workspace = true
clap.workspace = true
image = { workspace = true }
mimalloc.workspace = true
snafu.workspace = true
colog.workspace = true
prescript = { version = "0.1.0", path = "../prescript" }

[lints]
workspace = true
