[package]
name = "nipdf-test-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Used in nipdf-render to build test cases"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
glob.workspace = true
itertools.workspace = true

[lints]
workspace = true
