[package]
name = "nipdf-reader"
version = "0.1.0"
edition = "2021"
description = "iced pdf GUI reader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nipdf = { path = "../nipdf", version = "*" }
nipdf-render = { path = "../render", version = "*" }
env_logger.workspace = true
iced = { version = "0.13.1", features = ["image", "advanced"] }
directories-next = "2.0.0"
log.workspace = true
mimalloc.workspace = true
clap.workspace = true
snafu.workspace = true
prescript = { version = "0.1.0", path = "../prescript" }
rfd = "0.15.2"

[lints]
workspace = true
