[package]
name = "nipdf-reader"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "iced pdf GUI reader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nipdf = { path = "../nipdf" }
nipdf-render = { path = "../render" }
env_logger.workspace = true
iced = { version = "0.12.1", features = ["image"] }
iced_aw = { version = "0.9", default-features = false, features = [
    "modal",
    "card",
] }
directories-next = "2.0.0"
log.workspace = true
mimalloc.workspace = true
clap.workspace = true
snafu.workspace = true
prescript = { version = "0.1.0", path = "../prescript" }

[lints]
workspace = true
