[package]
name = "nipdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "0.4.3" }
thiserror = "1.0.40"
once_cell = "1.17.2"
itertools = "0.11.0"
nom = "7.1.3"
num = "0.4.0"
memchr = "2.5.0"
nohash-hasher = "0.2.0"
anyhow = "1.0.71"
ahash = "0.8.3"
flate2 = "1.0.26"
log = { version = "0.4.19", features = ["release_max_level_warn"] }
jpeg-decoder = "0.3.0"
image = { version = "0.24.6", default-features = false, features = [
    "png",
    "jpeg",
] }
env_logger = { version = "0.10.0", optional = true }
bitstream-io = "1.6.0"
strum = { version = "0.25.0", features = ["derive"] }
png = "0.17.9"
bitvec = "1.0.1"
jpeg2k = "0.6.6"
lazy_static = "1.4.0"
nipdf-macro = { path = "../nipdf-macro" }
arrayvec = "0.7.4"
tiny-skia = "0.11.2"
educe = "0.4.22"
pretty = { version = "0.12.1", optional = true }
bitflags = "2.4.0"
swash = "0.1.8"
fontdb = "0.15.0"
font-kit = { version = "0.11.0", features = ["loader-freetype"] }
pathfinder_geometry = "0.5.1"
weezl = "0.1.7"

[dev-dependencies]
env_logger = "0.10.0"
glob = "0.3.1"
insta = "1.29.0"
static_assertions = "1.1.0"
test-case = "3.1.0"
test-log = "0.2.12"
