[package]
name = "nipdf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "A PDF library written in Rust"
exclude = ["pdf.js", "sample_files"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex.workspace = true
once_cell.workspace = true
num-traits.workspace = true
memchr.workspace = true
ahash.workspace = true
log.workspace = true
jpeg-decoder.workspace = true
image.workspace = true
bitstream-io.workspace = true
strum.workspace = true
bitvec.workspace = true
jpeg2k.workspace = true
nipdf-macro = { path = "../macro", version = "0.1" }
nipdf-cff-parser = { path = "../cff-parser", version = "0.1" }
prescript = { path = "../prescript", version = "0.1" }
educe.workspace = true
pretty.workspace = true
bitflags.workspace = true
fontdb.workspace = true
font-kit.workspace = true
pathfinder_geometry.workspace = true
weezl.workspace = true
either.workspace = true
euclid.workspace = true
md-5.workspace = true
arc4.workspace = true
heck.workspace = true
paste.workspace = true
tinyvec.workspace = true
static_assertions.workspace = true
aes.workspace = true
cbc.workspace = true
phf.workspace = true
miniz_oxide.workspace = true
snafu.workspace = true
winnow.workspace = true
itertools.workspace = true
nipdf-jbig2dec = { version = "0.4.1", default-features = false }
encoding_rs = { version = "0.8.35" }
ordered-float = { version = "5.0.0", features = [ "bytemuck" ] }
bytemuck = "1.23.2"
append-only-vec = "0.1.7"
owned_ttf_parser = "0.25.1"
once_map = "0.4.22"

[dev-dependencies]
env_logger.workspace = true
glob.workspace = true
insta.workspace = true
assert_approx_eq.workspace = true
test-case.workspace = true
test-log.workspace = true
mockall = "0.13"
hex-literal.workspace = true

[lints]
workspace = true
